#!/bin/sh

# __author__ = "Jose Antonio Navas Molina"
# __copyright__ = "Copyright 2013, TaxSim project"
# __credits__ = ["Jose Antonio Navas Molina"]
# __license__ = "GPL"
# __version__ = "0.0.1-dev"
# __maintainer__ = "Jose Antonio Navas Molina"
# __email__ = "josenavasmolinao@gmail.com"

exec pyqi --driver-name TaxSim --command-config-module taxsim.interfaces.optparse.config -- "$@"